config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqa-composer-templates:
      branch: feature/dynamic_tool_gathering
      repo: https://github.com/EOSC-synergy/sqa-composer-templates
environment: {}
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - 'curl -H ''Accept: application/json'' -H ''Content-Type: application/json''
          -H ''Authorization: Basic bWFydmVsOndvbmRlcndvbWFu'' -X POST -d ''{"metadata_service_endpoint":"http://digital.csic.es/dspace-oai/request","metadata_service_type":"oai_pmh","object_identifier":"http://hdl.handle.net/10261/157765","test_debug":true,"use_datacite":true}''
          http://localhost:1071/fuji/api/v1/evaluate'
        container: qc.fair_bluesy-auburn-zebra
timeout: 600
